cloud:
  aws:
    region:
      static: us-west-1
      auto: false
    stack:
      auto: false
    credentials:
      secret-key: put your secret key here
      access-key: put your access key here
    endpoint:
      url: put queue name here
    bucket:
      name: student-s3-bucket


server:
  port: 8080
