cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      secret-key: put here your user secret key
      access-key: put here your user access key
    endpoint:
      url: put here your queue url



server:
  port:8080
