cloud:
  aws:
    region:
      static: us-west-1
      auto: false
    stack:
      auto: false
    credentials:
      secret-key: put your secret key here
      access-key: put your access key here
    endpoint:
      url: put your queue url here
      queue-name: student-crud-queue

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

server:
  port: 8083